name: release

on:
  workflow_dispatch:

jobs:
  release:
    name: release extension
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Nodejs
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: release
        run: npm run publish -- -p ${{ secrets.ADPAT }}
